from ...plugin import Plugin


class MecanumDrivePlugin(Plugin):
    def __init__(
            self,
            front_left_joint: list[str] | str | None = None,
            front_right_joint: list[str] | str | None = None,
            back_left_joint: list[str] | str | None = None,
            back_right_joint: list[str] | str | None = None,
            wheel_separation: float | None = None,
            wheelbase: float | None = None,
            wheel_radius: float | None = None,
            min_velocity: float | None = None,
            max_velocity: float | None = None,
            min_acceleration: float | None = None,
            max_acceleration: float | None = None,
            min_jerk: float | None = None,
            max_jerk: float | None = None,
            odom_publish_frequency: float | None = None,
            topic: str | None = None,
            odom_topic: str | None = None,
            tf_topic: str | None = None,
            frame_id: str | None = None,
            child_frame_id: str | None = None,
    ):
        super().__init__(
            sdf_version=None,
            filename="gz-sim-mecanum-drive-system",
            name="gz::sim::systems::MecanumDrive",
            front_left_joint=front_left_joint,
            front_right_joint=front_right_joint,
            back_left_joint=back_left_joint,
            back_right_joint=back_right_joint,
            wheel_separation=wheel_separation,
            wheelbase=wheelbase,
            wheel_radius=wheel_radius,
            min_velocity=min_velocity,
            max_velocity=max_velocity,
            min_acceleration=min_acceleration,
            max_acceleration=max_acceleration,
            min_jerk=min_jerk,
            max_jerk=max_jerk,
            odom_publish_frequency=odom_publish_frequency,
            topic=topic,
            odom_topic=odom_topic,
            tf_topic=tf_topic,
            frame_id=frame_id,
            child_frame_id=child_frame_id,
        )
